import type { Metadata } from "next";
import "./globals.css";
import Particles from "./components/particles";
import ImageTrail from "./components/image-trail";

export const metadata: Metadata = {
  title: "strikerate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{ backgroundColor: '#f1f2f2' }}
      >
        <Particles />
        <ImageTrail />
        <div className="container mx-auto relative">
          {children}
        </div>
      </body>
    </html>
  );
}
