import type { Metadata } from "next";
import "./globals.css";
import Particles from "./components/particles";
import ImageTrail from "./components/image-trail";

export const metadata: Metadata = {
  title: "strikerate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{ backgroundColor: '#f1f2f2' }}
      >
        <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center">
          <div className="container mx-auto relative">
          <div className="absolute inset-0 color-overlay"></div>
            <img src="/assets/hand-of-god.jpg" className="w-full h-full object-contain" style={{
              filter: "saturate(0.01)",
              opacity: 0.8,
            }} />
            <div className="absolute inset-0 fade-overlay"></div>
          </div>
        </div>
        <Particles />
        <ImageTrail />
        <div className="container mx-auto relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
